### ========== ###
# JOINT MATCHING #
### ========== ###

#Joint ids from `joint_states`: 
#expected order is: [Mh,HI,SI,HO,SO]
fr_joint_state_ids: [0,1,2,3,4]
rr_joint_state_ids: [5,6,7,8,9]
fl_joint_state_ids: [10,11,12,13,14]
rl_joint_state_ids: [15,16,16,18,19]

#motor ids. Expected order is: [Mh,HI,HO]
fr_motor_ids: [6,5,4]
rr_motor_ids: [12,11,10]
fl_motor_ids: [3,2,1]
rl_motor_ids: [9,8,7]

leg_order: [1,3,0,2] #[FR,RR,FL,RR] id of the corresponding leg

#Mh: MotorHousing
#HI: HipInner
#SI: ShankInner
#HO: HipOuter
#SO: ShankOuter

body_desired_pose_topic: "olympus/desired_angle"
body_current_pose_topic: "/qualisys/olympus/odom"
controller_mode : 1 #choose from [0: weld, 1: revolute_x, 2: revolute_y, 3: revolute_z, 4: floating]

### =========== ###
# Control Options #
### =========== ###

stabilization_mode: false
manoeuvre_target_torque: [3,0,0]

# contracting_param: [0.6, 0.5, 0.8, 0.5] #initial -> small movement
contracting_param: [0.75, 0.75, 0.75, 0.75]
# contracting_param: [1,1,1,1]

#Pitch (WIP)
# contracting_param: [0.5, 1, 0.5, 0.5] +1 #needs also offseting

# ROLL:
# contracting_roll: [0.8, 0.8, 0.8, 0.8] -> 2
# contracting_roll: [0.8, 0.8, 0.8, 0.8] -> -3

angular_offsets:
  roll: 40
  pitch: 0
  yaw: 30