### ========== ###
# JOINT MATCHING #
### ========== ###

#Joint ids from `joint_states`: 
#expected order is: [Mh,HI,SI,HO,SO]
fr_joint_state_ids: [0,1,2,3,4]
rr_joint_state_ids: [5,6,7,8,9]
fl_joint_state_ids: [10,11,12,13,14]
rl_joint_state_ids: [15,16,16,18,19]

#motor ids. Expected order is: [Mh,HI,HO]
fr_motor_ids: [6,5,4]
rr_motor_ids: [12,11,10]
fl_motor_ids: [3,2,1]
rl_motor_ids: [9,8,7]

leg_order: [1,3,0,2] #[FR,RR,FL,RR] id of the corresponding leg

#Mh: MotorHousing
#HI: HipInner
#SI: ShankInner
#HO: HipOuter
#SO: ShankOuter

body_desired_pose_topic: "olympus/desired_angle"
body_current_pose_topic: "/qualisys/olympus/odom"
controller_mode : 3 #choose from [0: weld, 1: revolute_x, 2: revolute_y, 3: revolute_z, 4: floating]

### =========== ###
# Control Options #
### =========== ###

stabilization_mode: false
manoeuvre_target_torque: [0,0,1]

# contracting_param: [0.6, 0.5, 0.8, 0.5] #initial -> small movement
contracting_param: [0.8, 0.8, 0.8, 0.8]

offset_roll: 40
offset_pitch: 0
offset_yaw: 0